### ISSUE TITLE
Installation instruction fix

### ISSUE THREAD

**Issue by Krishna** [yarshure/CoreImagePython#1]
First: thanks @yarshure for creating a GitHub repo for this - Apple seems to have removed links to this code. 🙄

This issue is just to raise awareness that the installation instruction in the README does not work, but the following will work:

`'python setup.py install'`

Hope this helps someone.

**Comment by gaseosaluz** [comment]
Thanks for the fix. I can confirm that this makes the (extensive) installation work. I installed it inside a `conda` environment. After the install completed, I can import the packages into the environment. I have not tested further but will do over the next few days.
